name: Pipeline IC y SonarQube
on:
  push:
    branches:
      - main
      - feature/cd-docker 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' 

      # AJUSTE: Instalación global directa (sin caché problemático)
      - name: Instalar SonarQube Cloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      # AJUSTE: Comando directo llamando a la herramienta global
      - name: Iniciar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner begin /k:"gusti233_ics-calculadora-ic-cd" /o:"gusti233" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Compilar (Build)
        run: dotnet build

      - name: Pruebas (Test)
        run: dotnet test

      - name: Finalizar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Construir Imagen Docker (CD)
        run: docker build -t calculadora-gpa:latest .