name: Pipeline IC y SonarQube
on:
  push:
    branches:
      - main
      - feature/testing-sdd
      - feature/cd-docker 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest # Cambiamos a ubuntu-latest porque compilar Docker en Linux es mucho más rápido y estándar

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' 

      - name: Cache de herramientas de SonarQube
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Instalar SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ~/.sonar/scanner

      - name: Iniciar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ~/.sonar/scanner/dotnet-sonarscanner begin /k:"gusti233_ics-calculadora-ic-cd" /o:"gusti233" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Compilar (Build)
        run: dotnet build

      - name: Pruebas (Test)
        run: dotnet test

      - name: Finalizar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ~/.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Construir Imagen Docker (CD)
        run: docker build -t calculadora-gpa:latest .